version: '3.8'

services:
  # FastAPI Backend
  propmatch-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - propmatch-network

  # Optional: Local Redis for development (using Redis Cloud in production)
  # Uncomment if you want to test with local Redis instead of Redis Cloud
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - propmatch-network

  # Optional: Local PostgreSQL for development
  # Uncomment if you want to use local database instead of Supabase
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: propmatch
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - propmatch-network

# volumes:
  # redis_data:
  # postgres_data:

networks:
  propmatch-network:
    driver: bridge 